version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: dss
      MONGO_INITDB_ROOT_PASSWORD: dss
      MONGODB_AUTH_DATABASE: allcarsinone
    ports:
      - "27017:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db

volumes:
  mongodb_data_volume:
    driver: local
